name: Basic Tests

on: [push, pull_request]

jobs:
  test:
    name: Basic functionality test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests flask flask-cors
      - name: Test Backend Import
        run: |
          python -c "import backend_server; print('Backend server imports successfully')"
      - name: Test Package Import
        run: |
          python -c "import instastorysaver; print('Package imports successfully')"
